"""QMIX: Monotonic Value Function Factorisation for cooperative MARL.

Decomposes joint Q-value into per-agent utilities via a monotonic mixing
network whose weights are generated by a hypernetwork conditioned on global
state. Monotonicity (dQ_tot/dQ_i >= 0) is enforced by taking abs() of
mixing weights.

Reference:
    T. Rashid, M. Samvelyan, C. Schroeder de Witt, G. Farquhar,
    J. Foerster, S. Whiteson,
    "QMIX: Monotonic Value Function Factorisation for Deep Multi-Agent
    Reinforcement Learning," ICML, 2018.
    https://arxiv.org/abs/1803.11485
"""

from __future__ import annotations

import copy
import sys
from typing import Any

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing import TypeVar
    Self = TypeVar("Self")

import gymnasium as gym
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from rlox.callbacks import Callback, CallbackList
from rlox.logging import LoggerCallback
from rlox.trainer import register_algorithm


# ---------------------------------------------------------------------------
# Per-agent Q-network
# ---------------------------------------------------------------------------


class AgentQNetwork(nn.Module):
    """Simple MLP Q-network for a single agent."""

    def __init__(self, obs_dim: int, n_actions: int, hidden_dim: int = 64) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, n_actions),
        )

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        """Return Q-values for all actions. Shape: (B, n_actions)."""
        return self.net(obs)


# ---------------------------------------------------------------------------
# Monotonic mixing network
# ---------------------------------------------------------------------------


class QMixer(nn.Module):
    """Hypernetwork-based mixing network with monotonicity constraint.

    Takes per-agent Q-values and global state, produces Q_tot.
    Weights are non-negative (abs) to guarantee monotonicity.

    Parameters
    ----------
    n_agents : int
        Number of agents.
    state_dim : int
        Dimension of the global state.
    mixing_embed_dim : int
        Hidden dimension of the mixing network (default 32).
    """

    def __init__(
        self,
        n_agents: int,
        state_dim: int,
        mixing_embed_dim: int = 32,
    ) -> None:
        super().__init__()
        self.n_agents = n_agents

        # Hypernetwork: state -> mixing weights (must be non-negative)
        self.hyper_w1 = nn.Sequential(
            nn.Linear(state_dim, mixing_embed_dim),
            nn.ReLU(),
            nn.Linear(mixing_embed_dim, n_agents * mixing_embed_dim),
        )
        self.hyper_b1 = nn.Linear(state_dim, mixing_embed_dim)

        self.hyper_w2 = nn.Sequential(
            nn.Linear(state_dim, mixing_embed_dim),
            nn.ReLU(),
            nn.Linear(mixing_embed_dim, mixing_embed_dim),
        )
        self.hyper_b2 = nn.Sequential(
            nn.Linear(state_dim, mixing_embed_dim),
            nn.ReLU(),
            nn.Linear(mixing_embed_dim, 1),
        )

        self.mixing_embed_dim = mixing_embed_dim

    def forward(
        self, agent_qs: torch.Tensor, global_state: torch.Tensor,
    ) -> torch.Tensor:
        """Mix per-agent Q-values into Q_tot.

        Parameters
        ----------
        agent_qs : (B, n_agents)
            Per-agent Q-values.
        global_state : (B, state_dim)
            Global state.

        Returns
        -------
        q_tot : (B, 1)
        """
        batch_size = agent_qs.shape[0]
        agent_qs = agent_qs.unsqueeze(1)  # (B, 1, n_agents)

        # First layer: abs() ensures non-negative weights -> monotonicity
        w1 = self.hyper_w1(global_state).abs()
        w1 = w1.view(batch_size, self.n_agents, self.mixing_embed_dim)
        b1 = self.hyper_b1(global_state).view(batch_size, 1, self.mixing_embed_dim)

        hidden = F.elu(torch.bmm(agent_qs, w1) + b1)  # (B, 1, embed)

        # Second layer
        w2 = self.hyper_w2(global_state).abs()
        w2 = w2.view(batch_size, self.mixing_embed_dim, 1)
        b2 = self.hyper_b2(global_state).view(batch_size, 1, 1)

        q_tot = torch.bmm(hidden, w2) + b2  # (B, 1, 1)
        return q_tot.squeeze(-1)  # (B, 1)


# ---------------------------------------------------------------------------
# Simple replay buffer for QMIX
# ---------------------------------------------------------------------------


class _QMIXReplayBuffer:
    """Minimal replay buffer storing per-agent observations and actions."""

    def __init__(self, capacity: int) -> None:
        self._capacity = capacity
        self._data: list[dict[str, Any]] = []
        self._pos = 0

    def push(self, transition: dict[str, Any]) -> None:
        if len(self._data) < self._capacity:
            self._data.append(transition)
        else:
            self._data[self._pos] = transition
        self._pos = (self._pos + 1) % self._capacity

    def sample(
        self, batch_size: int, rng: np.random.Generator,
    ) -> dict[str, torch.Tensor]:
        indices = rng.integers(0, len(self._data), size=batch_size)
        batch = [self._data[i] for i in indices]

        return {
            key: torch.stack([b[key] for b in batch])
            for key in batch[0]
        }

    def __len__(self) -> int:
        return len(self._data)


# ---------------------------------------------------------------------------
# QMIX algorithm
# ---------------------------------------------------------------------------


@register_algorithm("qmix")
class QMIX:
    """Value decomposition for cooperative multi-agent RL.

    Each agent has its own Q-network. A monotonic mixing network combines
    per-agent Q-values with the global state to produce Q_tot.

    Parameters
    ----------
    env_id : str
        Gymnasium environment ID (used for obs/action space detection).
    n_agents : int
        Number of agents (default 3).
    hidden_dim : int
        Hidden dimension for agent Q-networks (default 64).
    mixing_embed_dim : int
        Mixing network hidden dimension (default 32).
    learning_rate : float
        Adam learning rate (default 5e-4).
    buffer_size : int
        Replay buffer capacity (default 50_000).
    batch_size : int
        Minibatch size (default 32).
    gamma : float
        Discount factor (default 0.99).
    target_update_freq : int
        Steps between target network updates (default 200).
    epsilon_start : float
        Initial exploration epsilon (default 1.0).
    epsilon_end : float
        Final exploration epsilon (default 0.05).
    epsilon_decay_steps : int
        Steps over which epsilon decays (default 5000).
    seed : int
        Random seed (default 42).
    callbacks : list[Callback], optional
    logger : LoggerCallback, optional
    """

    def __init__(
        self,
        env_id: str,
        n_agents: int = 3,
        hidden_dim: int = 64,
        mixing_embed_dim: int = 32,
        learning_rate: float = 5e-4,
        buffer_size: int = 50_000,
        batch_size: int = 32,
        gamma: float = 0.99,
        target_update_freq: int = 200,
        epsilon_start: float = 1.0,
        epsilon_end: float = 0.05,
        epsilon_decay_steps: int = 5000,
        seed: int = 42,
        callbacks: list[Callback] | None = None,
        logger: LoggerCallback | None = None,
    ) -> None:
        self.env = gym.make(env_id)
        self.env_id = env_id
        self.n_agents = n_agents
        self.gamma = gamma
        self.batch_size = batch_size
        self.target_update_freq = target_update_freq
        self.epsilon_start = epsilon_start
        self.epsilon_end = epsilon_end
        self.epsilon_decay_steps = epsilon_decay_steps
        self.seed = seed

        # Seed torch/np/env RNG for reproducibility.  This MUST happen
        # before the agent/mixing networks are constructed below so that
        # their weight initialisation is deterministic for a given seed
        # (precedent: pqn.py:118, crossq.py:141).  Gymnasium does not
        # propagate `env.reset(seed=...)` to the action space's RNG, so
        # the action space gets its own `.seed()` call here too (defensive:
        # exploration in this algo is driven by the locally-seeded `rng` in
        # `train()`, not `action_space.sample()`, but this keeps the pattern
        # consistent across all gym.make-based algorithms in this codebase).
        torch.manual_seed(seed)
        np.random.seed(seed)
        self.env.action_space.seed(seed)

        obs_dim = int(np.prod(self.env.observation_space.shape))
        act_space = self.env.action_space
        self._obs_dim = obs_dim
        self.discrete = isinstance(act_space, gym.spaces.Discrete)

        if self.discrete:
            self.n_actions = int(act_space.n)
        else:
            raise ValueError("QMIX requires a discrete action space")

        # Per-agent Q-networks
        self.agent_networks = nn.ModuleList(
            [AgentQNetwork(obs_dim, self.n_actions, hidden_dim) for _ in range(n_agents)]
        )
        self.target_agent_networks = copy.deepcopy(self.agent_networks)

        # Mixing network
        state_dim = obs_dim * n_agents
        self.mixing_network = QMixer(n_agents, state_dim, mixing_embed_dim)
        self.target_mixing_network = copy.deepcopy(self.mixing_network)

        all_params = (
            list(self.agent_networks.parameters())
            + list(self.mixing_network.parameters())
        )
        self.optimizer = torch.optim.Adam(all_params, lr=learning_rate)

        self.buffer = _QMIXReplayBuffer(buffer_size)

        self.callbacks = CallbackList(callbacks)
        self.logger = logger
        self._global_step = 0

        self._config = {
            "n_agents": n_agents,
            "hidden_dim": hidden_dim,
            "mixing_embed_dim": mixing_embed_dim,
            "learning_rate": learning_rate,
            "buffer_size": buffer_size,
            "batch_size": batch_size,
            "gamma": gamma,
            "target_update_freq": target_update_freq,
            "epsilon_start": epsilon_start,
            "epsilon_end": epsilon_end,
            "epsilon_decay_steps": epsilon_decay_steps,
            "seed": seed,
        }

    def _get_epsilon(self, step: int) -> float:
        """Linearly decay epsilon."""
        frac = min(1.0, step / max(1, self.epsilon_decay_steps))
        return self.epsilon_start + frac * (self.epsilon_end - self.epsilon_start)

    def _select_actions(
        self, obs: np.ndarray, epsilon: float, rng: np.random.Generator,
    ) -> list[int]:
        """Epsilon-greedy action selection for each agent."""
        obs_t = torch.as_tensor(obs, dtype=torch.float32).unsqueeze(0)
        actions = []
        for i in range(self.n_agents):
            if rng.random() < epsilon:
                actions.append(rng.integers(self.n_actions))
            else:
                with torch.no_grad():
                    q_vals = self.agent_networks[i](obs_t)
                    actions.append(q_vals.argmax(dim=-1).item())
        return actions

    def train(self, total_timesteps: int) -> dict[str, float]:
        """Run QMIX training loop.

        Uses single env with shared observations (all agents see same state).

        Returns
        -------
        dict with 'loss' and 'mean_reward' keys.
        """
        rng = np.random.default_rng(self.seed)
        obs, _ = self.env.reset(seed=self.seed)
        episode_rewards: list[float] = []
        ep_reward = 0.0
        metrics: dict[str, float] = {}

        self.callbacks.on_training_start()

        for step in range(total_timesteps):
            epsilon = self._get_epsilon(step)
            actions = self._select_actions(np.asarray(obs, dtype=np.float32), epsilon, rng)

            # Use first agent's action for single env stepping
            env_action = actions[0]
            next_obs, reward, terminated, truncated, _ = self.env.step(env_action)
            ep_reward += float(reward)

            # Store transition
            obs_f = np.asarray(obs, dtype=np.float32)
            next_obs_f = np.asarray(next_obs, dtype=np.float32)

            transition = {
                "obs": torch.as_tensor(obs_f),
                "next_obs": torch.as_tensor(next_obs_f),
                "actions": torch.tensor(actions, dtype=torch.long),
                "reward": torch.tensor(float(reward)),
                "terminated": torch.tensor(float(terminated)),
                # Global state = replicated obs for all agents
                "global_state": torch.as_tensor(
                    np.tile(obs_f, self.n_agents).astype(np.float32)
                ),
                "next_global_state": torch.as_tensor(
                    np.tile(next_obs_f, self.n_agents).astype(np.float32)
                ),
            }
            self.buffer.push(transition)

            obs = next_obs
            if terminated or truncated:
                episode_rewards.append(ep_reward)
                ep_reward = 0.0
                obs, _ = self.env.reset()

            # Update
            if len(self.buffer) >= self.batch_size:
                metrics = self._update(rng)

            # Target network update
            if step % self.target_update_freq == 0:
                self.target_agent_networks.load_state_dict(
                    self.agent_networks.state_dict()
                )
                self.target_mixing_network.load_state_dict(
                    self.mixing_network.state_dict()
                )

            self._global_step += 1

        self.callbacks.on_training_end()

        metrics["mean_reward"] = (
            float(np.mean(episode_rewards)) if episode_rewards else 0.0
        )
        return metrics

    def _update(self, rng: np.random.Generator) -> dict[str, float]:
        """Single QMIX update step."""
        batch = self.buffer.sample(self.batch_size, rng)

        obs = batch["obs"]  # (B, obs_dim)
        next_obs = batch["next_obs"]
        actions = batch["actions"]  # (B, n_agents)
        reward = batch["reward"]  # (B,)
        terminated = batch["terminated"]  # (B,)
        global_state = batch["global_state"]  # (B, state_dim)
        next_global_state = batch["next_global_state"]

        # Compute per-agent Q-values for chosen actions
        agent_qs = []
        for i in range(self.n_agents):
            q_vals = self.agent_networks[i](obs)  # (B, n_actions)
            q_chosen = q_vals.gather(1, actions[:, i:i+1]).squeeze(-1)
            agent_qs.append(q_chosen)
        agent_qs = torch.stack(agent_qs, dim=1)  # (B, n_agents)

        q_tot = self.mixing_network(agent_qs, global_state)  # (B, 1)

        # Target
        with torch.no_grad():
            target_agent_qs = []
            for i in range(self.n_agents):
                target_q = self.target_agent_networks[i](next_obs)
                target_agent_qs.append(target_q.max(dim=-1).values)
            target_agent_qs = torch.stack(target_agent_qs, dim=1)

            target_q_tot = self.target_mixing_network(
                target_agent_qs, next_global_state
            )
            targets = reward.unsqueeze(-1) + self.gamma * (1.0 - terminated.unsqueeze(-1)) * target_q_tot

        loss = F.mse_loss(q_tot, targets)

        self.optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(
            list(self.agent_networks.parameters())
            + list(self.mixing_network.parameters()),
            10.0,
        )
        self.optimizer.step()

        return {"loss": loss.item()}

    def predict(
        self,
        obs: np.ndarray,
        deterministic: bool = True,
    ) -> list[int]:
        """Get actions for all agents given observation."""
        obs_t = torch.as_tensor(obs, dtype=torch.float32).unsqueeze(0)
        actions = []
        for i in range(self.n_agents):
            with torch.no_grad():
                q_vals = self.agent_networks[i](obs_t)
                actions.append(q_vals.argmax(dim=-1).item())
        return actions

    def save(self, path: str) -> None:
        """Save checkpoint."""
        torch.save(
            {
                "agent_networks": self.agent_networks.state_dict(),
                "mixing_network": self.mixing_network.state_dict(),
                "optimizer": self.optimizer.state_dict(),
                "step": self._global_step,
                "env_id": self.env_id,
                "config": self._config,
            },
            path,
        )

    @classmethod
    def from_checkpoint(cls, path: str, env_id: str | None = None) -> Self:
        """Restore from checkpoint."""
        from rlox.checkpoint import safe_torch_load

        data = safe_torch_load(path)
        eid = env_id or data.get("env_id", "CartPole-v1")
        config = data["config"]

        qmix = cls(env_id=eid, **config)
        qmix.agent_networks.load_state_dict(data["agent_networks"])
        qmix.mixing_network.load_state_dict(data["mixing_network"])
        qmix.optimizer.load_state_dict(data["optimizer"])
        qmix._global_step = data.get("step", 0)
        return qmix
